config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :affiliate_codes do
      member do
        get 'tag-report', action: 'tag_report', as: 'tag_report'
        post 'tag-report', action: 'tag_report', as: 'post_tag_report'
        get 'sku-report', action: 'sku_report', as: 'sku_report'
        post 'sku-report', action: 'sku_report', as: 'post_sku_report'
      end
    end
    resources :reports, :only => [:index] do
      collection do
        get :affiliate_source_report
        post :affiliate_source_report
        get :affiliate_tag_report
        post :affiliate_tag_report
      end
    end
  end
end

app/models/spree/affiliate_code.rb
module Spree
  class AffiliateCode < ActiveRecord::Base
    validates :code, presence: true, uniqueness: true
    validates :rate, presence: true, numericality: { greater_than_or_equal_to: 0, allow_nil: true }
  end
end

app/controllers/spree/admin/affiliate_codes_controller.rb
module Spree
  module Admin
    class AffiliateCodesController < Spree::Admin::ResourceController

      before_filter :load_affiliate_code, :only => [:update, :edit, :show, :destroy, :tag_report, :sku_report]

      def index
        @affiliate_code = Spree::AffiliateCode.new
        @affiliate_codes = Spree::AffiliateCode.all
      end

      def sku_report
        params[:q] = {} unless params[:q]
        if params[:q][:created_at_gt].blank?
          params[:q][:created_at_gt] = Time.zone.now.beginning_of_month
        else
          params[:q][:created_at_gt] = Time.zone.parse(params[:q][:created_at_gt]).beginning_of_day rescue Time.zone.now.beginning_of_month
        end
        if params[:q] && !params[:q][:created_at_lt].blank?
          params[:q][:created_at_lt] = Time.zone.parse(params[:q][:created_at_lt]).end_of_day rescue ""
        else
          params[:q][:created_at_lt] = Time.zone.now.end_of_day
        end
        params[:q][:campaign_tag_eq] = @affiliate_code.code

        @search = Spree::LineItem.all.ransack(params[:q])
        @line_items = @search.result
        @report = {}

        @line_items.each do |line_item|
          next if !line_item.order.complete?
          key = line_item.variant.sku
          @report[key] = {
            :price => 0,
            :quantity => 0,
            :total => 0,
            :commission => 0
          }
          @report[key][:price] = line_item.price
          @report[key][:quantity] += line_item.quantity
          @report[key][:total] += line_item.price
          @report[key][:commission] += (@affiliate_code.rate * line_item.price)
        end
      end

      def tag_report
        params[:q] = {} unless params[:q]
        if params[:q][:created_at_gt].blank?
          params[:q][:created_at_gt] = Time.zone.now.beginning_of_month
        else
          params[:q][:created_at_gt] = Time.zone.parse(params[:q][:created_at_gt]).beginning_of_day rescue Time.zone.now.beginning_of_month
        end
        if params[:q] && !params[:q][:created_at_lt].blank?
          params[:q][:created_at_lt] = Time.zone.parse(params[:q][:created_at_lt]).end_of_day rescue ""
        else
          params[:q][:created_at_lt] = Time.zone.now.end_of_day
        end
        params[:q][:completed_at_not_null] = '1'
        params[:q][:campaign_source_not_null] = '1'

        created_at_gt = params[:q][:created_at_gt].to_date
        created_at_lt = params[:q][:created_at_lt].to_date

        @search = Ransack::Search.new(Spree::Order)
        @report = {}
        @product_sum = 0
        @total = 0
        @commission_sum = 0
        created_at_gt.upto(created_at_lt) { |date|
          line_items = Spree::LineItem.where(created_at: (date.beginning_of_day..date.end_of_day), campaign_tag: @affiliate_code.code)
          @report[date] = {
            :product_sold => 0,
            :payable_order_value => 0,
            :commission => 0
          }
          line_items.each do |line_item|
            next if !line_item.order.complete?
            @report[date][:product_sold] += line_item.quantity
            @product_sum += line_item.quantity
            @report[date][:payable_order_value] += line_item.price
            @total += line_item.price
            @report[date][:commission] += (@affiliate_code.rate * line_item.price)
            @commission_sum += (@affiliate_code.rate * line_item.price)
          end
        }
        @report['Total'] = {
          :product_sold => @product_sum,
          :payable_order_value => @total,
          :commission => @commission_sum
        }
      end

      def show
        params[:q] = {} unless params[:q]
        if params[:q][:created_at_gt].blank?
          params[:q][:created_at_gt] = Time.zone.now.beginning_of_month
        else
          params[:q][:created_at_gt] = Time.zone.parse(params[:q][:created_at_gt]).beginning_of_day rescue Time.zone.now.beginning_of_month
        end
        if params[:q] && !params[:q][:created_at_lt].blank?
          params[:q][:created_at_lt] = Time.zone.parse(params[:q][:created_at_lt]).end_of_day rescue ""
        else
          params[:q][:created_at_lt] = Time.zone.now.end_of_day
        end
        params[:q][:completed_at_not_null] = '1'
        params[:q][:campaign_source_not_null] = '1'

        created_at_gt = params[:q][:created_at_gt].to_date
        created_at_lt = params[:q][:created_at_lt].to_date

        @search = Ransack::Search.new(Spree::Order)
        @report = {}
        @product_sum = 0
        @total = 0
        @commission_sum = 0
        created_at_gt.upto(created_at_lt) { |date|
          orders = Spree::Order.where(completed_at: (date.beginning_of_day..date.end_of_day), campaign_source: @affiliate_code.code)
          @report[date] = {
            :product_sold => 0,
            :payable_order_value => 0,
            :commission => 0
          }
          orders.each do |order|
            @report[date][:product_sold] += order.item_count
            @product_sum += order.item_count
            @report[date][:payable_order_value] += order.item_total
            @total += order.item_total
            @report[date][:commission] += (@affiliate_code.rate * order.item_total)
            @commission_sum += (@affiliate_code.rate * order.item_total)
          end
        }
        @report['Total'] = {
          :product_sold => @product_sum,
          :payable_order_value => @total,
          :commission => @commission_sum
        }
      end

      private
        def load_affiliate_code
          @affiliate_code = Spree::AffiliateCode.find(params[:id])
        end
    end
  end
end

app/views/spree/admin/affiliate_codes/edit.html.erb
<% content_for :page_title do %>
  <%= 'Edit Affiliate Code' %>
<% end %>

<%= form_for @affiliate_code, :url => admin_affiliate_code_path(@affiliate_code) do |f| %>
    <%= f.label :code %>:
    <%= f.text_field :code %>
    <%= f.label :rate %>:
    <%= f.text_field :rate %>
    <%= f.submit %>
<% end %>

app/views/spree/admin/affiliate_codes/index.html.erb
<% content_for :page_title do %>
  <%= 'Affiliate Codes' %>
<% end %>

<% content_for :page_actions do %>
  <%= form_for @affiliate_code, :url => admin_affiliate_codes_path do |f| %>
      <%= f.label :code %>:
      <%= f.text_field :code %>
      <%= f.label :rate %>:
      <%= f.text_field :rate %>
      <%= f.submit %>
  <% end %>
<% end %>

<% if @affiliate_codes.any? %>
  <table class="index">
    <colgroup>
      <col style="width: 50%">
      <col style="width: 50%">
    </colgroup>
    <thead>
      <tr data-hook="affiliate_codes_header">
        <th><%= 'Code' %></th>
        <th><%= 'Rate' %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @affiliate_codes.each do |affiliate_code|%>
      <tr id="affiliate_codes" data-hook="affiliate_codes_row" class="<%= cycle('odd', 'even')%>">
        <td class="align-center"><%= link_to affiliate_code.code, admin_affiliate_code_path(affiliate_code) %></td>
        <td class="align-center"><%= affiliate_code.rate %></td>
        <td class="actions">
          <%= link_to_edit affiliate_code, :no_text => true %>
          <%= link_to_delete affiliate_code, :no_text => true %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/tax_rate')) %>,
  </div>
<% end %>

app/views/spree/admin/affiliate_codes/show.html.erb
<% content_for :page_title do %>
  <%= 'Affiliate Code : ' + @affiliate_code.code %>
  <br/>
  <%= ' Rate : ' + @affiliate_code.rate.to_s %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'icon-edit', 'Edit', edit_admin_affiliate_code_path(@affiliate_code), :class => 'button' %></li>
  <li><%= link_to_with_icon 'icon-file', 'Tag Report', tag_report_admin_affiliate_code_path(@affiliate_code), :class => 'button' %></li>
  <li><%= link_to_with_icon 'icon-file', 'SKU Report', sku_report_admin_affiliate_code_path(@affiliate_code), :class => 'button' %></li>
<% end %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:date_range) %>
<% end %>

<% content_for :table_filter do %>
  <%= search_form_for @search, :url => admin_affiliate_code_path(@affiliate_code)  do |s| %>
    <div class="date-range-filter field align-center">
        <%= label_tag nil, Spree.t(:start), :class => 'inline' %>
        <%= s.text_field :created_at_gt, :class => 'datepicker datepicker-from' %>

        <span class="range-divider">
          <i class="icon-arrow-right"></i>
        </span>

        <%= s.text_field :created_at_lt, :class => 'datepicker datepicker-to' %>
        <%= label_tag nil, Spree.t(:end), :class => 'inline' %>
    </div>

    <div class="actions filter-actions">
      <%= button Spree.t(:search), 'icon-search'  %>
    </div>
  <% end %>
<% end %>

<table class="admin-report" data-hook="affiliate_total">
  <thead>
    <tr>
      <th>Date</th>
      <th>Products Sold</th>
      <th>Payable Order Value</th>
      <th>Commission</th>
    </tr>
  </thead>
  <% if !@report.blank? %>
    <% @report.each do |key, value| %>
    <tbody>
      <td><%= key %></td>
      <td><%= value[:product_sold] %></td>
      <td><%= value[:payable_order_value] %></td>
      <td><%= value[:commission] %></td>
    </tbody>
    <% end %>
  <% else %>
    No Codes Available
  <% end %>
</table>

app/views/spree/admin/affiliate_codes/sku_report.html.erb
<% content_for :page_title do %>
  <%= 'Affiliate Code : ' + @affiliate_code.code %>
  <br/>
  <%= ' Rate : ' + @affiliate_code.rate.to_s %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'icon-edit', 'Edit', edit_admin_affiliate_code_path(@affiliate_code), :class => 'button' %></li>
  <li><%= link_to_with_icon 'icon-file', 'Source Report', admin_affiliate_code_path(@affiliate_code), :class => 'button' %></li>
  <li><%= link_to_with_icon 'icon-file', 'Tag Report', tag_report_admin_affiliate_code_path(@affiliate_code), :class => 'button' %></li>
<% end %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:date_range) %>
<% end %>

<% content_for :table_filter do %>
  <%= search_form_for @search, :url => post_sku_report_admin_affiliate_code_path(@affiliate_code)  do |s| %>
    <div class="date-range-filter field align-center">
        <%= label_tag nil, Spree.t(:start), :class => 'inline' %>
        <%= s.text_field :created_at_gt, :class => 'datepicker datepicker-from' %>

        <span class="range-divider">
          <i class="icon-arrow-right"></i>
        </span>

        <%= s.text_field :created_at_lt, :class => 'datepicker datepicker-to' %>
        <%= label_tag nil, Spree.t(:end), :class => 'inline' %>
    </div>

    <div class="actions filter-actions">
      <%= button Spree.t(:search), 'icon-search'  %>
    </div>
  <% end %>
<% end %>

<table class="admin-report" data-hook="affiliate_total">
  <thead>
    <tr>
      <th>SKU</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total</th>
      <th>Commission</th>
    </tr>
  </thead>
  <% if !@report.blank? %>
    <% @report.each do |key, value| %>
    <tbody>
      <td><%= key %></td>
      <td><%= value[:price] %></td>
      <td><%= value[:quantity] %></td>
      <td><%= value[:total] %></td>
      <td><%= value[:commission] %></td>
    </tbody>
    <% end %>
  <% else %>
    No Codes Available
  <% end %>
</table>

app/views/spree/admin/affiliate_codes/tag_report.html.erb
<% content_for :page_title do %>
  <%= 'Affiliate Code : ' + @affiliate_code.code %>
  <br/>
  <%= ' Rate : ' + @affiliate_code.rate.to_s %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'icon-edit', 'Edit', edit_admin_affiliate_code_path(@affiliate_code), :class => 'button' %></li>
  <li><%= link_to_with_icon 'icon-file', 'Source Report', admin_affiliate_code_path(@affiliate_code), :class => 'button' %></li>
  <li><%= link_to_with_icon 'icon-file', 'SKU Report', sku_report_admin_affiliate_code_path(@affiliate_code), :class => 'button' %></li>
<% end %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:date_range) %>
<% end %>

<% content_for :table_filter do %>
  <%= search_form_for @search, :url => post_tag_report_admin_affiliate_code_path(@affiliate_code)  do |s| %>
    <div class="date-range-filter field align-center">
        <%= label_tag nil, Spree.t(:start), :class => 'inline' %>
        <%= s.text_field :created_at_gt, :class => 'datepicker datepicker-from' %>

        <span class="range-divider">
          <i class="icon-arrow-right"></i>
        </span>

        <%= s.text_field :created_at_lt, :class => 'datepicker datepicker-to' %>
        <%= label_tag nil, Spree.t(:end), :class => 'inline' %>
    </div>

    <div class="actions filter-actions">
      <%= button Spree.t(:search), 'icon-search'  %>
    </div>
  <% end %>
<% end %>

<table class="admin-report" data-hook="affiliate_total">
  <thead>
    <tr>
      <th>Date</th>
      <th>Products Sold</th>
      <th>Payable Order Value</th>
      <th>Commission</th>
    </tr>
  </thead>
  <% if !@report.blank? %>
    <% @report.each do |key, value| %>
    <tbody>
      <td><%= key %></td>
      <td><%= value[:product_sold] %></td>
      <td><%= value[:payable_order_value] %></td>
      <td><%= value[:commission] %></td>
    </tbody>
    <% end %>
  <% else %>
    No Codes Available
  <% end %>
</table>